### ISSUE TITLE
Root/drafts dirs won't be found if their paths contain symlinks

### ISSUE THREAD

**Issue by mattgemmell** [mattgemmell/Jekyll-Staging#2]
My Ruby-fu isn't quite up to this. My Dropbox folder is actually on another drive, but is symlinked into my home directory. Thus, the path:

 ~/Dropbox/blog/mattgemmell

is actually:

/Volumes/Files/matt/Dropbox/blog/mattgemmell

The script should accept those paths, and expand them appropriately. Before it was a gem, it used to work, but now it doesn't for some reason. I'm not sure why. File.expand_path() isn't doing the trick.

Any thoughts?

**Comment by mattgemmell** [comment]
Actually, I think this is a different issue. It _is_ expanding the path correctly, but it still reports that the dir doesn't exist (it definitely does). I'll look into it some more. Closing this for now.

**Comment by mattgemmell** [comment]
Turns out the loaded config values just needed stripped of whitespace. Fixed in https://github.com/mattgemmell/Jekyll-Staging/commit/864c86998b6e65022066205b378379f15e2f8f1d

**Comment by parkr** [comment]
@mattgemmell Glad you figured it out. It could have been caused by `STDIN.gets`. When you hit <kbd>Enter</kbd>, you create a newline. That newline is included in the return value from `STDIN.gets`, so that might be the root cause here.
