### ISSUE TITLE
Maybe make staging stateful

### ISSUE THREAD

**Issue by mattgemmell** [mattgemmell/Jekyll-Staging#3]
When staging, we could write out a `.jekyll-staging-active` file into the site root, containing YAML showing the original path of the currently-staged draft, and its current staged path (in _posts).

When unstaging, we'd remove that file. If the raw unstage command was used, without a filename glob, we could preferentially act on the post specified in the `-active` file. This would help ensure that staging and unstaging are symmetrical operations.

If staging was attempted and we already find an `-active` file, we could warn and ask the user if they want to continue regardless. Other programs/gems/plugins could also use the `-active` file as an indicator of whether staging is currently enabled, and customise their functionality appropriately.

I don't see this being a problem for source control, since presumably users aren't going to do a commit whilst staging anyway (since all their posts will have been temporarily moved aside).

Thoughts welcomed.

**Comment by parkr** [comment]
Would the existence of the `_stash` directory and it containing at least one file constitute an active staging state? I'm wondering if it is possible to achieve this state and customization with filesystem state already part of the tool.

**Comment by mattgemmell** [comment]
That's what I've been advising people to do since last night, yeah. I'm struggling to think of a case where the filesystem wouldn't be a good enough indicator.

Changing settings underneath the script (while a stage was in progress) is pathological, and even then you'd probably want an unstage to target the new drafts directory anyway.

It just seems a little ugly for a theoretical external program to have to check for the stash dir's existence, then its contents, but I guess it's no worse than having to know the name of the hypothetical 'active' file.

Still worth doing the check itself within the script, and asking for confirmation about going ahead anyway (default to aborting).

**Comment by mattgemmell** [comment]
Went ahead with just doing a filesystem check in https://github.com/mattgemmell/Jekyll-Staging/commit/153547b797b38d957abfc21b395282ea9f6c38bc

Gem version 1.0.3 also pushed to rubygems.
